### ISSUE TITLE
npm simple install and require :(

### ISSUE THREAD

**Issue by fast0490f** [newoga/material-ui-scrolling-techniques#2]
Hi, I tried to use npm i material-ui-scrolling-techniques, but failed. Poor that have to make changes to the configuration webpack. I wanted a simple use.

**Comment by newoga** [comment]
@fast0490f This project is not available in `npm`. It is prototype only (with the intention of including in material-ui in the future). If there is anything you want to use, you have to include the source code yourself.

**Comment by stunaz** [comment]
`material-ui` is missing you
